### ISSUE TITLE
Port conflict on 5738 for biobuddy and rosettafold

### ISSUE THREAD

**Issue by arsen3d** [BasedLabs/NoLabs#92]
```
  biobuddy:
    image: 'ghcr.io/basedlabs/biobuddy:1.2.1'
    network_mode: host
    build:
      context: microservices/biobuddy
      dockerfile: build/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    command: --host=0.0.0.0 --port=5738
  rosettafold:
    image: 'ghcr.io/basedlabs/rosettafold:1.0.0'
    network_mode: host
    build:
      context: microservices/rosettafold
      dockerfile: build/Dockerfile
    volumes:
      - /media/jt/Local Disk/RoseTTAFold/bfd:/RoseTTAFold/bfd
      - /media/jt/Local Disk/RoseTTAFold/pdb100_2021Mar03:/RoseTTAFold/pdb100_2021Mar03
      - /media/jt/Local Disk/RoseTTAFold/UniRef30_2020_06:/RoseTTAFold/UniRef30_2020_06
    command: --host=0.0.0.0 --port=5738
    
```
